create extension if not exists pgtap with schema extensions;
begin;
select plan(18);
select has_extension('pgcrypto');
select has_table('public'::name, 'chord_packs'::name);
select col_is_pk('public'::name, 'chord_packs'::name, 'id'::name);
select has_column('public'::name, 'chord_packs'::name, 'ownership_token_hash'::name, 'ownership_token_hash');
select has_column('public'::name, 'chord_packs'::name, 'chords'::name, 'chords');
select has_function('private', 'normalize_pack_payload', array['jsonb']);
select has_function('private', 'public_pack_json', array['public.chord_packs']);
select is((select relrowsecurity from pg_class where oid = 'public.chord_packs'::regclass), true);
select table_privs_are('public', 'chord_packs', 'anon', array[]::text[]);
select table_privs_are('public', 'chord_packs', 'authenticated', array[]::text[]);
select lives_ok($$ select private.normalize_pack_payload('{"packName":"Pack","authorName":"","tags":["Jazz"],"key":"C","trackSoundName":"Warm Pad","sourceTrackIndex":7,"chords":[{"slotIndex":1,"notes":[60],"displayName":"C"},{"slotIndex":2,"notes":[60],"displayName":"C"},{"slotIndex":3,"notes":[60],"displayName":"C"},{"slotIndex":4,"notes":[60],"displayName":"C"},{"slotIndex":5,"notes":[60],"displayName":"C"},{"slotIndex":6,"notes":[60],"displayName":"C"},{"slotIndex":7,"notes":[60],"displayName":"C"}]}'::jsonb) $$);
select is(private.normalize_pack_payload('{"packName":"Pack","authorName":"","tags":[],"key":"C","trackSoundName":"Pad","chords":[{"slotIndex":1,"notes":[60],"displayName":"C"},{"slotIndex":2,"notes":[60],"displayName":"C"},{"slotIndex":3,"notes":[60],"displayName":"C"},{"slotIndex":4,"notes":[60],"displayName":"C"},{"slotIndex":5,"notes":[60],"displayName":"C"},{"slotIndex":6,"notes":[60],"displayName":"C"},{"slotIndex":7,"notes":[60],"displayName":"C"}]}'::jsonb)->>'authorName', 'Anonymous');
select throws_ok($$ select private.normalize_pack_payload('{}'::jsonb) $$, '22023');
select throws_ok($$ select private.normalize_pack_payload(jsonb_build_object('packName', repeat('x', 101))) $$, '22023');
select throws_ok($$ select private.normalize_pack_payload(jsonb_build_object('packName','P','authorName','A','tags',jsonb_build_array('Jazz','jazz'),'key','C','trackSoundName','Pad','chords','[]'::jsonb)) $$, '22023');
select throws_ok($$ select private.normalize_pack_payload(jsonb_build_object('packName','P','authorName','A','tags','[]'::jsonb,'key','H','trackSoundName','Pad','chords','[]'::jsonb)) $$, '22023');
select throws_ok($$ select private.normalize_pack_payload(jsonb_build_object('packName','P','authorName','A','tags','[]'::jsonb,'key','C','trackSoundName','Pad','chords',jsonb_build_array(jsonb_build_object('slotIndex',1,'notes',jsonb_build_array(35),'displayName','C')))) $$, '22023');
set local role anon;
select throws_ok($$ insert into public.chord_packs(pack_name,author_name,tags,musical_key,track_sound_name,chords,ownership_token_hash) values ('P','A','{}','C','Pad','[]','hash') $$, '42501');
reset role;
select * from finish();
rollback;
